ipynb-filters: [nbprocess_filter]

project:
  type: website
  output-dir: docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "nbprocess"
  sidebar:
    style: "floating"
    search: true

metadata-files: 
  - sidebar.yml

