ipynb-filters: [filter.py]

project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "nbprocess"
  sidebar:
    style: "floating"
    search: true
    contents:
      - 01_read.ipynb
      - 02_maker.ipynb
      - 03_process.ipynb
      - 04_export.ipynb
      - 05_sync.ipynb
      - 06_merge.ipynb
      - 07_clean.ipynb
      - 08_processors.ipynb
      - 09_filter.ipynb
      - index.ipynb